module.exports = {
  INITIALIZE: "INITIALIZE",

  ADD_PROJECT: "ADD_PROJECT",

  EDIT_PROJECT: "EDIT_PROJECT",

  DELETE_PROJECT: "DELETE_PROJECT",

  ADD_BUILD: "ADD_BUILD",

  EDIT_BUILD: "EDIT_BUILD",
};
